# Generated by Django 3.0.2 on 2020-04-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200421_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='group',
            new_name='org',
        ),
    ]
