# Generated by Django 3.0.2 on 2020-04-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200421_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='org',
            new_name='group',
        ),
    ]
