# Generated by Django 3.0.2 on 2020-04-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200421_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='formio_usergroup',
            field=models.CharField(blank=True, default='libtech', max_length=256, null=True),
        ),
    ]
