# Generated by Django 3.0.2 on 2020-04-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_formio_usergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='region',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
    ]
