# Generated by Django 3.0.2 on 2020-04-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200422_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='region',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
