# Generated by Django 3.0.2 on 2020-04-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200423_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_user_manager',
            field=models.BooleanField(default=False),
        ),
    ]
