# Generated by Django 3.0.2 on 2020-04-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_is_user_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='formio_usergroup',
            field=models.CharField(blank=True, default='wassan', max_length=256, null=True),
        ),
    ]
