# Generated by Django 3.0.2 on 2020-05-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200428_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wasan_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
