# Generated by Django 3.0.2 on 2020-05-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200506_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='group',
            new_name='team',
        ),
    ]
