# Generated by Django 3.0.2 on 2020-05-18 18:25

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_team_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='data_json',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='extra_fields',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='prefill_json',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
