# Generated by Django 3.0.2 on 2020-03-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
