# Generated by Django 3.0.2 on 2020-03-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_auto_20200331_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='contact_numbers',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='how_urgent',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
