# Generated by Django 3.0.2 on 2020-03-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_auto_20200331_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='what_help',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
