# Generated by Django 3.0.2 on 2020-03-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_auto_20200331_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='who_are_you',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
