# Generated by Django 3.0.2 on 2020-03-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_auto_20200331_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='record_type',
            field=models.CharField(blank=True, default='needHelp', max_length=1024, null=True),
        ),
    ]
