# Generated by Django 3.0.2 on 2020-03-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_context_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='icon_url',
            field=models.URLField(blank=True, default='http://maps.google.com/mapfiles/ms/icons/red-dot.png', null=True),
        ),
    ]
