# Generated by Django 3.0.2 on 2020-04-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_auto_20200401_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
