# Generated by Django 3.0.2 on 2020-04-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_context_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='is_functional',
            field=models.BooleanField(default=True),
        ),
    ]
