# Generated by Django 3.0.2 on 2020-04-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0012_context_is_functional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='icon_url',
            field=models.URLField(blank=True, default='https://covidb.libtech.in/media/icons/red-dot.png', null=True),
        ),
    ]
