# Generated by Django 3.0.2 on 2020-04-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0013_auto_20200401_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='backend_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
