# Generated by Django 3.0.2 on 2020-04-02 13:28

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0019_auto_20200402_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='data_json',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
