# Generated by Django 3.0.2 on 2020-04-03 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0021_auto_20200402_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='feedback_form',
        ),
    ]
