# Generated by Django 3.0.2 on 2020-04-03 23:37

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0022_remove_entity_feedback_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='feedback_form_json',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
