# Generated by Django 3.0.2 on 2020-04-10 11:11

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0024_auto_20200403_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='data_json',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
