# Generated by Django 3.0.2 on 2020-04-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0025_entity_data_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
