# Generated by Django 3.0.2 on 2020-04-10 15:49

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0028_auto_20200410_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='google_location_json',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
