# Generated by Django 3.0.2 on 2020-04-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0029_auto_20200410_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
