# Generated by Django 3.0.2 on 2020-04-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0030_entity_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='name',
            new_name='title',
        ),
    ]
