# Generated by Django 3.0.2 on 2020-04-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0031_auto_20200416_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='full_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='org_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
