# Generated by Django 3.0.2 on 2020-04-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0035_entity_prefill_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='formio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
