# Generated by Django 3.0.2 on 2020-04-18 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0036_entity_formio_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityBulkEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_action', models.CharField(blank=True, max_length=256, null=True)),
                ('data_json', django_mysql.models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('entities', models.ManyToManyField(to='baseapp.Entity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entityBulkEdit',
            },
        ),
    ]
