# Generated by Django 3.0.2 on 2020-04-18 12:24

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0037_entitybulkedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='extra_fields',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='from_ui',
            field=models.BooleanField(default=True),
        ),
    ]
