# Generated by Django 3.0.2 on 2020-04-18 13:48

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0038_auto_20200418_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitybulkedit',
            name='data_json',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
