# Generated by Django 3.0.2 on 2020-04-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0043_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
