# Generated by Django 3.0.2 on 2020-04-20 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0044_delete_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='assigned_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
