# Generated by Django 3.0.2 on 2020-04-21 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0045_entity_assigned_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='assigned_to_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.Entity'),
        ),
    ]
