# Generated by Django 3.0.2 on 2020-04-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0046_entity_assigned_to_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='assigned_to_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_assignment', to='baseapp.Entity'),
        ),
    ]
