# Generated by Django 3.0.2 on 2020-04-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0048_auto_20200421_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='region',
        ),
    ]
