# Generated by Django 3.0.2 on 2020-04-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0049_remove_entity_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
