# Generated by Django 3.0.2 on 2020-04-21 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200421_1353'),
        ('baseapp', '0050_delete_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_entity', to='core.Region'),
        ),
    ]
