# Generated by Django 3.0.2 on 2020-04-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0052_entity_assigned_to_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='formio_usergroup',
            field=models.CharField(blank=True, default='libtech', max_length=256, null=True),
        ),
    ]
