# Generated by Django 3.0.2 on 2020-04-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0054_remove_entity_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='region',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='state',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
