# Generated by Django 3.0.2 on 2020-04-27 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0056_entity_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EntityHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_help', models.CharField(blank=True, max_length=1024, null=True)),
                ('user_name', models.CharField(blank=True, max_length=256, null=True)),
                ('data_json', django_mysql.models.JSONField(default=dict)),
                ('status', models.CharField(blank=True, max_length=256, null=True)),
                ('urgency', models.CharField(blank=True, max_length=1024, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.Entity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entityhistory',
            },
        ),
    ]
