# Generated by Django 3.0.2 on 2020-05-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0058_auto_20200427_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='wassan_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
