# Generated by Django 3.0.2 on 2020-05-03 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0059_entity_wassan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
