# Generated by Django 3.0.2 on 2020-05-03 23:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0060_entity_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityhistory',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
