# Generated by Django 3.0.2 on 2020-05-09 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_team_organization'),
        ('baseapp', '0064_auto_20200509_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityhistory',
            name='assigned_to_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eh_org_group', to='core.Team'),
        ),
        migrations.AddField(
            model_name='entityhistory',
            name='assigned_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='es_user_assignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entityhistory',
            name='updated_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='es_user_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
