# Generated by Django 3.0.2 on 2020-05-18 11:49

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0066_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='route',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
