# Generated by Django 3.0.2 on 2020-05-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0070_pledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='amount_pending',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
